version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: devops-demo-api:local
    environment:
      DB_HOST: db
      DB_NAME: appdb
      DB_USER: appuser
      DB_PASSWORD: apppass
      DB_PORT: "5432"
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  dbdata:
