name: CD
on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"
      - "docker/**"
      - "helm/**"

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: ap-south-1
      ECR_REPO: devops-demo-api
      HELM_RELEASE: api
      NAMESPACE: demo
      CLUSTER_NAME: devops-demo

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:${{ github.sha }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

      - name: Helm upgrade
        run: |
          helm -n $NAMESPACE upgrade --install $HELM_RELEASE ./helm/app-chart \
            --set image.repository=${{ steps.login-ecr.outputs.registry }}/${ECR_REPO} \
            --set image.tag=${{ github.sha }}
        id: helm-upgrade
